import Head from "next/head";

import {api} from "~/utils/api";
import {CreatePostWizzard} from "~/components/CreatePostWizzard";
import {PostView} from "~/components/PostView";

export default function Home() {

    const {data, isLoading} = api.post.getAllPosts.useQuery()

    if (!data || isLoading) {
        return <div>Loading ...</div>
    }


    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main
                className="flex justify-center h-screen">
                <div className="w-full md:max-w-2xl border-x border-slate-400 h-full">
                    <div className="border-b border-slate-400 p-4 flex gap-4 align-middle">
                        <CreatePostWizzard/>
                    </div>
                    <div className="flex flex-col">
                        {data?.map((fullPost) => (
                            <PostView {...fullPost} key={fullPost.post.id} />
                        ))}
                    </div>
                </div>
            </main>
        </>
    );
}
